"""
Created on Oct. 29, 2021
by Giulio Iannello

Developed by Massimo Capurro Lladò

This program anonimizes a log file generated by moodle 


Expected json data:
Date/Time,
User name
Involved User
Event context
Component
Event
Description
Origin
IP adress
"""


import json

#This function reads the json file and saves its data into a list of lists

def ReadJsonFile(file):
    fin = open(file)
    log_list = json.load(fin)
    fin.close()
    return log_list

#This function saves data onto a new json file

def SaveJsonFile(file, data):
    fout = open(file, 'w')
    json.dump(data, fout, indent=2)
    fout.close()
    
#This function checks if there is a User Name. If it's missing fills the field with the Involved user 
def UserMissing(log):
    if(log[1]=='-' and log[2] != '-'):
        log[1], log[2]= log[2], log[1]

""" 
This function takes the log list as parameter and for every log switches
the Name of the User with a progressive code and deletes the involved user

"""

def Anonimize(log_list):
    log_list= log_list[0]
    code_tab = {}
    code = 1
    for log in log_list:
        UserMissing(log)
        if not log[1] in code_tab:
            code_tab[log[1]] = str(code).zfill(5)
            code += 1
        log.remove(log[2])
        log[1] = code_tab[log[1]]
    return code_tab



jsonFile = 'indata/anonimizza_test1.json'
log_list = ReadJsonFile(jsonFile)
code_tab = Anonimize(log_list)
SaveJsonFile('indata/anonymized1.json', log_list)
SaveJsonFile('indata/code_table.json', code_tab)

print("Task Ended")
